server:
  port: 9001
spring:
  application:
    name: hrm-sysmanage
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssj
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:com/zyc/hrm/mapper/*Mapper.xml
  type-aliases-package: com.zyc.hrm.domain,com.zyc.hrm.query
